repos: # install via pre-commit install ( https://pre-commit.com )
  - repo: local
    hooks:
      - id: yamllint
        name: yamllint
        entry: yamllint -c .yamllint-config.yml .
        language: python
        types: [file, yaml]
