# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  name: !secret homeassistant_name
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: !secret homeassistant_timezone
  external_url: !secret homeassistant_external_url
  internal_url: !secret homeassistant_internal_url
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.147/32
      trusted_users:
        192.168.1.147: 387e66a8ee7342d59914ff295ad6f78d
      allow_bypass_login: true
  whitelist_external_dirs:
    - /tmp

# lovelace:
#   mode: yaml
# logger:
#   default: critical


# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp

recorder:
  db_url: !secret db_url
  auto_purge: false
  exclude:
    domains:
      - automation
      - group
    entities:
      - sensor.date_time
      - sensor.time
      - sensor.room_1_climate
      - sensor.room_2_climate
      - sensor.room_3_climate
      - sensor.kitchen_climate
      - sensor.toilet_climate
      - sensor.bathroom_climate
      - sensor.hall_climate
      - sensor.corner_climate
      - sensor.door_climate
      - sensor.outdoor_climate

climate: !include include/climate.yaml
light: !include include/light.yaml
switch: !include include/switch.yaml
binary_sensor: !include_dir_merge_list include/binary_sensor
sensor: !include_dir_merge_list include/sensor
input_boolean: !include include/input_boolean.yaml
input_number: !include include/input_number.yaml
input_text: !include include/input_text.yaml
input_select: !include include/input_select.yaml
notify: !include include/notity.yaml
group: !include include/groups.yaml
automation: !include_dir_merge_list include/automations
script: !include include/scripts.yaml
scene: !include include/scenes.yaml
alarm_control_panel: !include include/alarm_control_panel.yaml
rest_command: !include include/rest_command.yaml
shell_command: !include include/shell_command.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies: !secret upstream_proxy

history:
  exclude:
    domains:
      - automation
      - group
    entities:
      - sensor.date_time
      - sensor.time
      - input_text.room1_ir_gate_url
      - sensor.co2_raw
      - input_text.narodmon_mac
      - input_text.narodmon_name
      - input_text.homeassistant_elevation
      - binary_sensor.room_1_occupied
      - sensor.room_1_climate
      - sensor.room_2_climate
      - sensor.room_3_climate
      - sensor.kitchen_climate
      - sensor.toilet_climate
      - sensor.bathroom_climate
      - sensor.hall_climate
      - sensor.corner_climate
      - sensor.door_climate
      - sensor.outdoor_climate

logbook:
  exclude:
    entities:
      - automation.mega_1_query_1w_bus
      - automation.mega_1_cmd_fix
      - automation.mega_1_cmd_fix_bri
      - binary_sensor.toilet_motion
      - binary_sensor.bathroom_motion
      - sensor.date_time
      - sensor.time
      - input_text.room1_ir_gate_url
      - sensor.co2_raw
      - input_text.narodmon_mac
      - input_text.narodmon_name
      - input_text.homeassistant_elevation
      - binary_sensor.room_1_occupied
      - sensor.room_1_climate
      - sensor.room_2_climate
      - sensor.room_3_climate
      - sensor.kitchen_climate
      - sensor.toilet_climate
      - sensor.bathroom_climate
      - sensor.hall_climate
      - sensor.corner_climate
      - sensor.door_climate
      - sensor.outdoor_climate

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_user
  password: !secret mqtt_password
  client_id: !secret mqtt_client_id


media_player:
  - platform: yamaha
    host: !secret media_yahaha_host
    source_names:
      AUDIO1: "HDMI ARC"
      HDMI1: "NVIDIA SHIELD"
    source_ignore:
      - "Alexa"
      - "Amazon Music"
      - "Deezer"
      - "Napster"
      - "PHONO"
      - "Qobuz"
      - "TIDAL"
    zone_ignore:
      - "Zone_2"

webostv:
  host: !secret media_lgtv_host
  name: "LG TV"

home_connect:
  client_id: !secret homeconnect_client_id
  client_secret: !secret homeconnect_client_secret


homekit:
  name: "HASS Bridge"
  filter:
    include_entities:
      - sensor.outdoor_temp
      - light.led_yellow
      - light.led
      - light.bulbs
      - climate.mitsubishi_heavy

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chatid_my

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret
