- alias: 'Trigger alarm while armed away'
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.room_1_door
        - binary_sensor.room_2_door
        - binary_sensor.room_3_door
        - binary_sensor.kitchen_door
        - binary_sensor.bathroom_door
        - binary_sensor.toilet_door
        - binary_sensor.main_door
        - binary_sensor.kitchen_top_storage_door
        - binary_sensor.bathroom_motion
        - binary_sensor.toilet_motion
        - binary_sensor.door_motion
        - binary_sensor.corner_motion
        - binary_sensor.room1_motion
        - binary_sensor.room2_motion
        - binary_sensor.room3_motion
        - binary_sensor.hall_motion
        - binary_sensor.kitchen_motion
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: armed_away
  action:
    - service: input_text.set_value
      data_template:
        entity_id: input_text.trigger_source
        value: "{{ trigger.to_state.attributes.friendly_name }}"
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.alarm

- alias: 'Trigger alarm while armed home'
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.main_door
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: armed_home
  action:
    service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.alarm

- alias: Inhome security notification
  trigger:
    platform: state
    entity_id:
      - binary_sensor.room_1_door
      - binary_sensor.room_2_door
      - binary_sensor.room_3_door
      - binary_sensor.kitchen_door
      - binary_sensor.bathroom_door
      - binary_sensor.toilet_door
      - binary_sensor.hall_storage_door
  condition: "{{ is_state('input_boolean.inhome_security', 'on') }}"
  action:
    - service: notify.notify_all
      data:
        message: >
          Sensor {{ trigger.to_state.attributes.friendly_name }} changed to {{ trigger.to_state.attributes.friendly_name }}!
