- alias: 'Send notification when alarm triggered'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm
      to: 'triggered'
  action:
    - service: notify.notify_all
      data:
        message: "ALARM! The alarm has been triggered by the {{ states('input_text.trigger_source') }} at {{ states('sensor.date_time') }}"

- alias: 'Send notification when alarm is Disarmed'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm
      to: 'disarmed'
  action:
    - service: notify.notify_all
      data:
        message: "ALARM! The alarm is Disarmed at {{ states('sensor.date_time') }}"

- alias: 'Send notification when alarm is in pending status'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm
      to: 'pending'
  action:
    - service: notify.notify_all
      data:
        message: "ALARM! The alarm is in pending status by the {{ states('input_text.trigger_source') }} at {{ states('sensor.date_time') }}"

- alias: 'Send notification when alarm is Armed in Away mode'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm
      to: 'armed_away'
  action:
    - service: notify.notify_all
      data:
        message: "ALARM! The alarm is armed in Away mode {{ states('sensor.date_time') }}"

- alias: 'Send notification when alarm is Armed in Home mode'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm
      to: 'armed_home'
  action:
    - service: notify.notify_all
      data:
        message: >
          ALARM! The alarm is armed in Home mode {{ states('sensor.date_time') }}
