- alias: Bathroom door trigger
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_door
  condition: "{{ is_state('input_boolean.bathroom_led_auto', 'on') }}"
  action:
    service: light.turn_on
    data:
      entity_id: light.bathroom_light_led
      brightness_pct: "{{ states('input_number.bathroom_led_bri') | int }}"

- alias: Bathroom door timeout trigger
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_door
    for:
      seconds: 7
  condition:
    - "{{ is_state('input_boolean.bathroom_led_auto', 'on') }}"
    - condition: state
      entity_id: binary_sensor.bathroom_motion
      state: 'off'
  action:
    service: light.turn_off
    entity_id: light.bathroom_light_led

- alias: Bathroom motion trigger
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_motion
    to: 'on'
  condition: "{{ is_state('input_boolean.bathroom_led_auto', 'on') }}"
  action:
    service: light.turn_on
    data:
      entity_id: light.bathroom_light_led
      brightness_pct: "{{ states('input_number.bathroom_led_bri') | int }}"

- alias: Bathroom closed motion off trigger
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_motion
    to: 'off'
    for:
      minutes: 5
  condition:
    - "{{ is_state('input_boolean.bathroom_led_auto', 'on') }}"
    - condition: state
      entity_id: binary_sensor.bathroom_door
      state: 'off'
  action:
    service: light.turn_off
    entity_id: light.bathroom_light_led

- alias: Bathroom open motion off trigger
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_motion
    to: 'off'
    for:
      seconds: 30
  condition:
    - "{{ is_state('input_boolean.bathroom_led_auto', 'on') }}"
    - condition: state
      entity_id: binary_sensor.bathroom_door
      state: 'on'
  action:
    service: light.turn_off
    entity_id: light.bathroom_light_led

- alias: Bathroom LED sync brightness
  trigger:
    platform: state
    entity_id: input_number.bathroom_led_bri
  condition:
    - "{{ is_state('input_boolean.bathroom_led_auto', 'on') }}"
    - "{{ is_state('light.bathroom_light_led', 'on') }}"
  action:
    service: light.turn_on
    data:
      entity_id: light.bathroom_light_led
      brightness_pct: "{{ states('input_number.bathroom_led_bri') | int }}"

- alias: Bathroom LED on
  trigger:
    platform: state
    entity_id: light.bathroom_light_led
    to: 'on'
  action:
    service: light.turn_on
    data:
      entity_id: light.bathroom_mirror_light_led
      brightness_pct: "{{ states('input_number.bathroom_led_bri') | int }}"

- alias: Bathroom LED off
  trigger:
    platform: state
    entity_id: light.bathroom_light_led
    to: 'off'
  action:
    - service: light.turn_off
      entity_id: light.bathroom_mirror_light_led
    - service: switch.turn_off
      entity_id: switch.bathroom_mirror_heater

- alias: Bathroom on mirror heater
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_door
    to: 'off'
    for:
      seconds: 20
  condition:
    - "{{ is_state('light.bathroom_light_led', 'on') }}"
  action:
    service: switch.turn_on
    entity_id: switch.bathroom_mirror_heater

- alias: Bathroom mirror LED button
  mode: single
  max_exceeded: silent
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_mirror_switch
  condition: "{{ ( as_timestamp(now()) - as_timestamp(states.switch.bathroom_mirror_heater.last_changed) |int(0) ) < 1 }}"
  action:
    - service: light.turn_on
      data:
        entity_id: light.bathroom_mirror_light_led
        brightness_pct: "{%if state_attr('light.bathroom_mirror_light_led', 'brightness')|int == 255%}{%if is_state('light.bathroom_light_led', 'on')%}{{ states('input_number.bathroom_led_bri') | int }}{%else%}0{%endif%}{%else%}100{%endif%}"
    - delay: '00:00:01'
