- alias: Bathroom door trigger
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_door
  condition: "{{ is_state('input_boolean.bathroom_led_auto', 'on') }}"
  action:
    service: light.turn_on
    data:
      entity_id: light.bathroom_light_led
      brightness_pct: "{{ states('input_number.bathroom_led_bri') | int }}"

- alias: Bathroom door timeout trigger
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_door
    for:
      seconds: 7
  condition:
    - "{{ is_state('input_boolean.bathroom_led_auto', 'on') }}"
    - condition: state
      entity_id: binary_sensor.bathroom_motion
      state: 'off'
  action:
    service: light.turn_off
    entity_id: light.bathroom_light_led

- alias: Bathroom motion trigger
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_motion
    to: 'on'
  condition: "{{ is_state('input_boolean.bathroom_led_auto', 'on') }}"
  action:
    service: light.turn_on
    data:
      entity_id: light.bathroom_light_led
      brightness_pct: "{{ states('input_number.bathroom_led_bri') | int }}"

- alias: Bathroom closed motion off trigger
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_motion
    to: 'off'
    for:
      minutes: 5
  condition:
    - "{{ is_state('input_boolean.bathroom_led_auto', 'on') }}"
    - condition: state
      entity_id: binary_sensor.bathroom_door
      state: 'off'
  action:
    service: light.turn_off
    entity_id: light.bathroom_light_led

- alias: Bathroom open motion off trigger
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_motion
    to: 'off'
    for:
      seconds: 30
  condition:
    - "{{ is_state('input_boolean.bathroom_led_auto', 'on') }}"
    - condition: state
      entity_id: binary_sensor.bathroom_door
      state: 'on'
  action:
    service: light.turn_off

    entity_id: light.bathroom_light_led
