- alias: Hall motion trigger
  trigger:
    platform: state
    entity_id: binary_sensor.hall_motion
    to: 'on'
  condition:
    - "{{ is_state('input_boolean.hall_led_auto', 'on') }}"
  action:
    service: light.turn_on
    data:
      entity_id: light.hall_light_led
      brightness_pct: "{{ states('input_number.hall_led_bri') | int }}"

- alias: Hall motion off trigger
  trigger:
    platform: state
    entity_id: binary_sensor.hall_motion
    to: 'off'
    for:
      seconds: 10
  condition:
    - "{{ is_state('input_boolean.hall_led_auto', 'on') }}"
  action:
    service: light.turn_off
    entity_id: light.hall_light_led

- alias: Hall LED sync brightness
  trigger:
    platform: state
    entity_id: input_number.hall_led_bri
  condition:
    - "{{ is_state('input_boolean.hall_led_auto', 'on') }}"
    - "{{ is_state('light.hall_light_led', 'on') }}"
  action:
    service: light.turn_on
    data:
      entity_id: light.hall_light_led
      brightness_pct: "{{ states('input_number.hall_led_bri') | int }}"

- alias: Hall storage light on
  trigger:
    platform: state
    entity_id: binary_sensor.hall_storage_door
    to: 'on'
  action:
    service: light.turn_on
    data:
      entity_id: light.hall_storage_light_led
      brightness_pct: 100

- alias: Hall storage light off
  trigger:
    platform: state
    entity_id: binary_sensor.hall_storage_door
    to: 'off'
  action:
    service: light.turn_off
    entity_id: light.hall_storage_light_led

- alias: Hall light switch hall
  trigger:
    platform: state
    entity_id: binary_sensor.hall_light_switch_hall
  action:
    service: light.turn_on
    data:
      entity_id:
        - light.hall_bulb
        - light.hall_light_led
      brightness_pct: "{%if trigger.to_state.state == 'off' %}0{%else%}100{%endif%}"
