- alias: Hall motion trigger
  trigger:
    platform: state
    entity_id: binary_sensor.hall_motion
    to: 'on'
  condition:
    - "{{ is_state('input_boolean.hall_led_auto', 'on') }}"
  action:
    service: light.turn_on
    data:
      entity_id: light.hall_light_led
      brightness_pct: "{{ states('input_number.hall_led_bri') | int }}"

- alias: Hall motion off trigger
  trigger:
    platform: state
    entity_id: binary_sensor.hall_motion
    to: 'off'
    for:
      seconds: 10
  condition:
    - "{{ is_state('input_boolean.hall_led_auto', 'on') }}"
  action:
    service: light.turn_off
    entity_id: light.hall_light_led

- alias: Hall LED sync brightness
  trigger:
    platform: state
    entity_id: input_number.hall_led_bri
  condition:
    - "{{ is_state('input_boolean.hall_led_auto', 'on') }}"
    - "{{ is_state('light.hall_light_led', 'on') }}"
  action:
    service: light.turn_on
    data:
      entity_id: light.hall_light_led
      brightness_pct: "{{ states('input_number.hall_led_bri') | int }}"
