- alias: "Humidifier"
  trigger:
    platform: time_pattern
    minutes: '/30'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.humidifier
    - delay: '00:05:00'
    - service: switch.turn_off
      data:
        entity_id: switch.humidifier
