- alias: Kitchen work light
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_work_light_button
    to: 'on'
  action:
    service: light.toggle
    data:
      entity_id: light.kitchen_work_light_led
      brightness_pct: 100

- alias: Kitchen top storage light on
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_top_storage_door
    to: 'on'
  action:
    service: light.turn_on
    data:
      entity_id: light.kitchen_top_storage_light_led
      brightness_pct: 100

- alias: Kitchen top storage light off
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_top_storage_door
    to: 'off'
  action:
    service: light.turn_off
    entity_id: light.kitchen_top_storage_light_led

- alias: Kitchen vent by CO2
  mode: restart
  trigger:
    platform: state
    entity_id: sensor.kitchen_co2
  condition:
    - "{{ is_state('input_boolean.kitchen_led_auto', 'on') }}"
    - "{{ states('sensor.kitchen_co2') | float > 1400 }}"
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.kitchen_vent
    - delay: '00:10:00'
    - service: switch.turn_off
      data:
        entity_id: switch.kitchen_vent

- alias: Kitchen vent by humidity
  mode: restart
  trigger:
    platform: state
    entity_id:
      - sensor.kitchen_humidity
      - sensor.hall_humidity
  condition:
    - "{{ is_state('input_boolean.kitchen_led_auto', 'on') }}"
    - "{{ states('sensor.kitchen_humidity') | float - states('sensor.hall_humidity') | float > 10 }}"
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.kitchen_vent
    - delay: '00:10:00'
    - service: switch.turn_off
      data:
        entity_id: switch.kitchen_vent

- alias: Kitchen fridge storage light
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_fridge_storage_door
  action:
    service: light.turn_on
    data:
      entity_id: light.kitchen_fridge_storage_light_led
      brightness_pct: "{%if trigger.to_state.state == 'off' %}0{%else%}100{%endif%}"

- alias: Kitchen work light
  mode: restart
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_workspace_motion
  action:
    - service: light.turn_on
      data:
        entity_id: light.kitchen_work_light_led
        brightness_pct: 100
    - delay: '00:01:00'
    - service: light.turn_off
      data:
        entity_id: light.kitchen_work_light_led

- alias: Kitchen light left
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_switch_left
  action:
    - service: "light.turn_{% if trigger.to_state.state == 'active' %}on{%else%}off{%endif%}"
      entity_id: light.kitchen_left

- alias: Kitchen light center
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_switch_center
  action:
    - service: "light.turn_{% if trigger.to_state.state == 'active' %}on{%else%}off{%endif%}"
      entity_id: light.kitchen_center

- alias: Kitchen light right
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_switch_right
  action:
    - service: "light.turn_{% if trigger.to_state.state == 'active' %}on{%else%}off{%endif%}"
      entity_id: light.kitchen_right
