- alias: Mega-3 online monitor
  trigger:
    platform: state
    entity_id: binary_sensor.mega_3_online
    to: 'off'
    for:
      seconds: 5
  action:
    - service: notify.notify_all
      data:
        message: "Warning! Mega-3 is offline"
