- alias: Query Mega-1 on start
  trigger:
    platform: homeassistant
    event: start
  action:
    repeat:
      count: '37'
      sequence:
        - service: mqtt.publish
          data_template:
            topic: "mega1/cmd"
            payload: 'get:{{ repeat.index }}'
        - delay:
            milliseconds: 300

- alias: Mega-1 CMD Fix
  mode: queued
  trigger:
    platform: mqtt
    topic: "megad_mqtt_bridge/mega1/cmd-ext/#"
  action:
    service: mqtt.publish
    data_template:
      topic: "megad_mqtt_bridge/mega1/cmd"
      payload: '{{ trigger.topic|replace("megad_mqtt_bridge/mega1/cmd-ext/","") }}:{{ trigger.payload }}'

- alias: Mega-1 CMD Fix BRI
  mode: queued
  trigger:
    platform: mqtt
    topic: "megad_mqtt_bridge/mega1/cmd-ext-bri/#"
  action:
    service: mqtt.publish
    data_template:
      topic: "megad_mqtt_bridge/mega1/cmd"  # old bri 6.4262 (max 4095) current 7.12 (max 3003)
      payload: "{{ trigger.topic|replace('megad_mqtt_bridge/mega1/cmd-ext-bri/','') }}:{% set bri = trigger.payload | int %}{%if bri==0%}0{%else%}{% set out =  ((bri / 7.12) **  (1 / 0.33)) | round(1, 'floor') | int %}{% if out == 0 and bri > 0%}7{% else %}{{ out + 7 }}{% endif %}{% endif %}"

- alias: Mega-1 action on AC loss
  trigger:
    platform: state
    entity_id: binary_sensor.mega_1_ac
    to: 'off'
  action:
    - service: light.turn_off
      entity_id:
        - light.kitchen_work_light_led
        - light.kitchen_top_storage_light_led
        - light.hall_storage_light_led
        - light.bathroom_mirror_light_led
    - service: input_number.set_value
      data:
        value: 40
        entity_id:
          - input_number.bathroom_led_bri
          - input_number.toilet_led_bri
    - service: input_number.set_value
      data:
        value: 10
        entity_id:
          - input_number.hall_led_bri

- alias: Mega-1 notify on AC change
  trigger:
    platform: state
    entity_id: binary_sensor.mega_1_ac
  action:
    - service: notify.notify_all
      data:
        message: "Warning! Mega-1 AC is {%if trigger.to_state.state == 'on'%}online{%else%}offline{%endif%}"

- alias: Mega-1 notify on battery change
  trigger:
    platform: state
    entity_id: binary_sensor.mega_1_battery
  action:
    - service: notify.notify_all
      data:
        message: "Warning! Mega-1 battery is {%if trigger.to_state.state == 'on'%}low{%else%}normal{%endif%}"
