- alias: Tion mode mixed
  trigger:
    platform: state
    entity_id: sensor.room_1_co2
  condition:
    - "{{ is_state('binary_sensor.mega_2_ac', 'on') }}"
    - "{{ is_state('input_boolean.tion_auto', 'on') }}"
    - "{{ is_state('input_select.tion3s_mode', 'Indoor') }}"
    - "{{ trigger.to_state.state | int > 900 }}"
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.tion3s_mode
        option: 'Mixed'

- alias: Tion mode indoor
  trigger:
    platform: state
    entity_id: sensor.room_1_co2
  condition:
    - "{{ is_state('binary_sensor.mega_2_ac', 'on') }}"
    - "{{ is_state('input_boolean.tion_auto', 'on') }}"
    - "{{ is_state('input_select.tion3s_mode', 'Mixed') or is_state('input_select.tion3s_mode', 'Outdoor') }}"
    - "{{ trigger.to_state.state | int < 700 }}"
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.tion3s_mode
        option: 'Indoor'

- alias: Tion auto speed
  trigger:
    platform: state
    entity_id: sensor.room_1_co2
  condition:
    - "{{ is_state('binary_sensor.mega_2_ac', 'on') }}"
    - "{{ is_state('input_boolean.tion_auto', 'on') }}"
    - "{{ is_state('input_select.tion3s_mode', 'Mixed') or is_state('input_select.tion3s_mode', 'Outdoor') }}"
    - "{{ trigger.to_state.state | int >  900 }}"
  action:
    service: input_number.set_value
    data:
      entity_id: input_number.tion3s_fan_speed
      value: "{%set v = trigger.to_state.state|int%}{%set s = states('input_number.tion3s_fan_speed')|int%}{%set l = s*100+800%}{%set t = ((v-900)/100)|round(0, 'ceil')%}{%if t>s or (l-50)>v%}{%if t>6%}6{%else%}{{t}}{%endif%}{%else%}{{s}}{%endif%}"
