- alias: Toilet door trigger
  trigger:
    platform: state
    entity_id: binary_sensor.toilet_door
  condition:
    - "{{ is_state('input_boolean.toilet_led_auto', 'on') }}"
    - "{{ is_state('binary_sensor.hall_light_switch_toilet', 'off') }}"
  action:
    service: light.turn_on
    data:
      entity_id: light.toilet_light_led
      brightness_pct: "{{ states('input_number.toilet_led_bri') | int }}"

- alias: Toilet door timeout trigger
  trigger:
    platform: state
    entity_id: binary_sensor.toilet_door
    for:
      seconds: 7
  condition:
    - "{{ is_state('input_boolean.toilet_led_auto', 'on') }}"
    - "{{ is_state('binary_sensor.hall_light_switch_toilet', 'off') }}"
    - condition: state
      entity_id: binary_sensor.toilet_motion
      state: 'off'
  action:
    service: light.turn_off
    entity_id: light.toilet_light_led

- alias: Toilet motion trigger
  trigger:
    platform: state
    entity_id: binary_sensor.toilet_motion
    to: 'on'
  condition:
    - "{{ is_state('input_boolean.toilet_led_auto', 'on') }}"
    - "{{ is_state('binary_sensor.hall_light_switch_toilet', 'off') }}"
  action:
    service: light.turn_on
    data:
      entity_id: light.toilet_light_led
      brightness_pct: "{{ states('input_number.toilet_led_bri') | int }}"

- alias: Toilet closed motion off trigger
  trigger:
    platform: state
    entity_id: binary_sensor.toilet_motion
    to: 'off'
    for:
      minutes: 5
  condition:
    - "{{ is_state('input_boolean.toilet_led_auto', 'on') }}"
    - "{{ is_state('binary_sensor.hall_light_switch_toilet', 'off') }}"
    - condition: state
      entity_id: binary_sensor.toilet_door
      state: 'off'
  action:
    service: light.turn_off
    entity_id: light.toilet_light_led

- alias: Toilet open motion off trigger
  trigger:
    platform: state
    entity_id: binary_sensor.toilet_motion
    to: 'off'
    for:
      seconds: 30
  condition:
    - "{{ is_state('input_boolean.toilet_led_auto', 'on') }}"
    - "{{ is_state('binary_sensor.hall_light_switch_toilet', 'off') }}"
    - condition: state
      entity_id: binary_sensor.toilet_door
      state: 'on'
  action:
    service: light.turn_off
    entity_id: light.toilet_light_led

- alias: Toilet LED sync brightness
  trigger:
    platform: state
    entity_id: input_number.toilet_led_bri
  condition:
    - "{{ is_state('input_boolean.toilet_led_auto', 'on') }}"
    - "{{ is_state('binary_sensor.hall_light_switch_toilet', 'off') }}"
    - "{{ is_state('light.toilet_light_led', 'on') }}"
  action:
    service: light.turn_on
    data:
      entity_id: light.toilet_light_led
      brightness_pct: "{{ states('input_number.toilet_led_bri') | int }}"

- alias: Toilet vent by motion
  trigger:
    platform: state
    entity_id: binary_sensor.toilet_motion
    to: 'on'
  condition:
    - "{{ is_state('input_boolean.toilet_led_auto', 'on') }}"
    - "{{ is_state('light.toilet_light_led', 'on') }}"
    - "{{ is_state('binary_sensor.toilet_door', 'off') }}"
  action:
    - service: script.set_timer
      data:
        entity_id: timer.toilet_vent
        duration: 600
