- alias: Toilet door trigger
  trigger:
    platform: state
    entity_id: binary_sensor.toilet_door
    to: 'on'
  condition: "{{ is_state('input_boolean.toilet_led_auto', 'on') }}"
  action:
    service: light.turn_on
    data:
      entity_id: light.toilet_light_led
      brightness_pct: "{{ states('input_number.toilet_led_bri') | int }}"

- alias: Toilet door off trigger
  trigger:
    platform: state
    entity_id: binary_sensor.toilet_door
    to: 'off'
    for:
      seconds: 7
  condition:
    - "{{ is_state('input_boolean.toilet_led_auto', 'on') }}"
    - condition: state
      entity_id: binary_sensor.toilet_motion
      state: 'off'
  action:
    service: light.turn_off
    entity_id: light.toilet_light_led

- alias: Toilet motion trigger
  trigger:
    platform: state
    entity_id: binary_sensor.toilet_motion
    to: 'on'
  condition:
    - "{{ is_state('input_boolean.toilet_led_auto', 'on') }}"
    - condition: state
      entity_id: binary_sensor.toilet_door
      state: 'off'
  action:
    service: light.turn_on
    data:
      entity_id: light.toilet_light_led
      brightness_pct: "{{ states('input_number.toilet_led_bri') | int }}"

- alias: Toilet motion off trigger
  trigger:
    platform: state
    entity_id: binary_sensor.toilet_motion
    to: 'off'
    for:
      minutes: 1
  condition:
    - "{{ is_state('input_boolean.toilet_led_auto', 'on') }}"
    - condition: state
      entity_id: binary_sensor.toilet_door
      state: 'off'
  action:
    service: light.turn_off
    entity_id: light.toilet_light_led

- alias: Toilet LED sync brightness
  trigger:
    platform: state
    entity_id: input_number.toilet_led_bri
  condition:
    - "{{ is_state('input_boolean.toilet_led_auto', 'on') }}"
    - "{{ is_state('light.toilet_light_led', 'on') }}"
  action:
    service: light.turn_on
    data:
      entity_id: light.toilet_light_led
      brightness_pct: "{{ states('input_number.toilet_led_bri') | int }}"

- alias: Toilet vent on
  trigger:
    platform: state
    entity_id: binary_sensor.toilet_door
    to: 'off'
    for:
      seconds: 10
  condition:
    - "{{ is_state('input_boolean.toilet_led_auto', 'on') }}"
    - "{{ is_state('light.toilet_light_led', 'on') }}"
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.toilet_vent

- alias: Toilet vent off
  trigger:
    platform: state
    entity_id: binary_sensor.toilet_door
    to: 'off'
    for:
      minutes: 10
  condition:
    - "{{ is_state('input_boolean.toilet_led_auto', 'on') }}"
    - "{{ is_state('light.toilet_light_led', 'off') }}"
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.toilet_vent
