- alias: Bathroom vent sync with timer
  trigger:
    platform: state
    entity_id: timer.bathroom_vent
  action:
    - service: "fan.turn_{% if trigger.to_state.state == 'active' %}on{%else%}off{%endif%}"
      data:
        entity_id: fan.bathroom

- alias: Kitchen vent sync with timer
  trigger:
    platform: state
    entity_id: timer.kitchen_vent
  action:
    - service: "fan.turn_{% if trigger.to_state.state == 'active' %}on{%else%}off{%endif%}"
      data:
        entity_id: fan.kitchen

- alias: Toilet vent sync with timer
  trigger:
    platform: state
    entity_id: timer.toilet_vent
  action:
    - service: "fan.turn_{% if trigger.to_state.state == 'active' %}on{%else%}off{%endif%}"
      data:
        entity_id: fan.toilet

- alias: Adjust bathroom vent speed
  mode: restart
  trigger:
    platform: state
    entity_id:
      - light.bathroom_light_led
      - fan.bathroom
  condition:
    - "{{ is_state('fan.bathroom', 'on') }}"
    - "{{ is_state('input_boolean.bathroom_led_auto', 'on') }}"
  action:
    - delay: '00:00:01'
    - service: fan.set_percentage
      target:
        entity_id: fan.bathroom
      data:
        percentage: "{%if is_state('light.bathroom_light_led', 'on') %}40{%else%}100{%endif%}"

- alias: Adjust toilet vent speed
  mode: restart
  trigger:
    platform: state
    entity_id:
      - light.toilet_light_led
      - fan.toilet
  condition:
    - "{{ is_state('fan.toilet', 'on') }}"
    - "{{ is_state('input_boolean.toilet_led_auto', 'on') }}"
  action:
    - delay: '00:00:01'
    - service: fan.set_percentage
      target:
        entity_id: fan.toilet
      data:
        percentage: "{%if is_state('light.toilet_light_led', 'on') %}40{%else%}100{%endif%}"

- alias: Adjust kitchen vent speed
  mode: restart
  trigger:
    platform: state
    entity_id:
      - binary_sensor.kitchen_occupied
      - fan.kitchen
  condition:
    - "{{ is_state('fan.kitchen', 'on') }}"
    - "{{ is_state('input_boolean.toilet_led_auto', 'on') }}"
  action:
    - delay: '00:00:01'
    - service: fan.set_percentage
      target:
        entity_id: fan.kitchen
      data:
        percentage: "{%if is_state('binary_sensor.kitchen_occupied', 'on') %}20{%else%}100{%endif%}"
