- platform: mqtt
  state_topic: "mega2/30"
  value_template: "{{ value_json.value }}"
  name: "Door motion"
  device_class: motion
  unique_id: "binary_sensor.door_motion"

- platform: mqtt
  state_topic: "mega2/31"
  value_template: "{{ value_json.value }}"
  name: "Main door"
  device_class: door
  unique_id: "binary_sensor.main_door"
