- platform: mqtt
  state_topic: "mega1/5"
  value_template: "{{ value_json.value }}"
  name: "Hall motion"
  device_class: motion
  unique_id: "binary_sensor.hall_motion"

- platform: mqtt
  state_topic: "mega1/38"
  value_template: "{{ value_json.value }}"
  payload_off: "ON"
  payload_on: "OFF"
  name: "Hall storage door"
  device_class: door
  unique_id: "binary_sensor.hall_storage_door"
