- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega1/5"
  value_template: "{{ value_json.value }}"
  name: "Hall motion"
  device_class: motion
  unique_id: "binary_sensor.hall_motion"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega1/38"
  value_template: "{{ value_json.value }}"
  payload_off: "ON"
  payload_on: "OFF"
  name: "Hall storage door"
  device_class: door
  unique_id: "binary_sensor.hall_storage_door"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega3/15"
  value_template: "{{ value_json.value }}"
  name: "Hall Light Switch Toilet"
  unique_id: "binary_sensor.hall_light_switch_toilet"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega3/16"
  value_template: "{{ value_json.value }}"
  name: "Hall Light Switch Bathroom"
  unique_id: "binary_sensor.hall_light_switch_bathroom"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega3/17"
  value_template: "{{ value_json.value }}"
  name: "Hall Light Switch Hall"
  unique_id: "binary_sensor.hall_light_switch_hall"
