- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega3/30"
  value_template: "{{ value_json.value }}"
  name: "Kitchen work light button"
  unique_id: "binary_sensor.kitchen_work_light_button"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega3/4"
  value_template: "{{ value_json.value }}"
  payload_off: "ON"
  payload_on: "OFF"
  name: "Kitchen door"
  device_class: door
  unique_id: "binary_sensor.kitchen_door"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega1/17"
  value_template: "{{ value_json.value }}"
  name: "Kitchen moisture"
  device_class: moisture
  unique_id: "binary_sensor.kitchen_moisture"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega3/2"
  value_template: "{{ value_json.value }}"
  name: "Kitchen motion"
  device_class: motion
  unique_id: "binary_sensor.kitchen_motion"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega1/30"
  value_template: "{{ value_json.value }}"
  payload_off: "ON"
  payload_on: "OFF"
  name: "Kitchen top storage door"
  device_class: door
  unique_id: "binary_sensor.kitchen_top_storage_door"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega3/8"
  value_template: "{{ value_json.value }}"
  payload_off: "ON"
  payload_on: "OFF"
  name: "Kitchen fridge storage door"
  device_class: door
  unique_id: "binary_sensor.kitchen_fridge_storage_door"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega3/7"
  value_template: "{{ value_json.value }}"
  name: "Kitchen workspace motion"
  device_class: motion
  unique_id: "binary_sensor.kitchen_workspace_motion"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega3/11"
  value_template: "{{ value_json.value }}"
  name: "Kitchen Switch Left"
  unique_id: "binary_sensor.kitchen_switch_l"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega3/10"
  value_template: "{{ value_json.value }}"
  name: "Kitchen Switch Center"
  unique_id: "binary_sensor.kitchen_switch_c"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega3/9"
  value_template: "{{ value_json.value }}"
  name: "Kitchen Switch Right"
  unique_id: "binary_sensor.kitchen_switch_r"
