- platform: mqtt
  state_topic: "mega1/#"
  value_template: "{% if value[0] == '{' %}ON{% else %}{% endif %}"
  name: "Mega 1 online"
  device_class: connectivity
  off_delay: 60
  unique_id: "binary_sensor.mega1_online"

- platform: mqtt
  state_topic: "mega1/35"
  value_template: "{{ value_json.value }}"
  name: "Mega 1 AC"
  device_class: power
  unique_id: "binary_sensor.mega1_ac"

- platform: mqtt
  state_topic: "mega1/34"
  value_template: "{{ value_json.value }}"
  name: "Mega 1 Battery"
  device_class: battery
  unique_id: "binary_sensor.mega1_battery"
