- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega3/#"
  value_template: "{% if value[0] == '{' %}ON{% else %}{% endif %}"
  name: "Mega 3 online"
  device_class: connectivity
  off_delay: 60
  unique_id: "binary_sensor.mega3_online"
