- platform: template
  sensors:
    energy_cheap:
      friendly_name: "Cheap energy"
      device_class: power
      value_template: "{% set hour = states('sensor.time').split(':')[0] | int %}{% if is_state('binary_sensor.workday_sensor', 'on') and hour >= 17 and hour < 22 %}off{% else %}on{% endif %}"
    room_1_occupied:
      friendly_name: "Room 1 occupied"
      value_template: "{{ is_state('binary_sensor.room_1_motion','on') }}"
      delay_off: 3000
      device_class: occupancy
    kitchen_occupied:
      friendly_name: "Kitchen occupied"
      value_template: "{{ is_state('binary_sensor.kitchen_motion','on') }}"
      delay_off: 60
      device_class: occupancy
