- platform: mqtt
  state_topic: "mega1/31"
  value_template: "{{ value_json.value }}"
  name: "Toilet door"
  device_class: door
  unique_id: "binary_sensor.toilet_door"

- platform: mqtt
  state_topic: "mega1/7"
  value_template: "{{ value_json.value }}"
  name: "Toilet motion"
  device_class: motion
  unique_id: "binary_sensor.toilet_motion"

- platform: mqtt
  state_topic: "mega1/12"
  value_template: "{{ value_json.value }}"
  name: "Kitchen motion"
  device_class: motion
  unique_id: "binary_sensor.kitchen_motion"

- platform: mqtt
  state_topic: "mega1/15"
  value_template: "{{ value_json.value }}"
  name: "Bathroom moisture"
  device_class: moisture
  unique_id: "binary_sensor.bathroom_moisture"

- platform: mqtt
  state_topic: "mega1/16"
  value_template: "{{ value_json.value }}"
  name: "Toilet moisture"
  device_class: moisture
  unique_id: "binary_sensor.toilet_moisture"

- platform: mqtt
  state_topic: "mega1/17"
  value_template: "{{ value_json.value }}"
  name: "Kitchen moisture"
  device_class: moisture
  unique_id: "binary_sensor.kitchen_moisture"

- platform: mqtt
  state_topic: "mega1/11"
  value_template: "{{ value_json.value }}"
  payload_off: "ON"
  payload_on: "OFF"
  name: "Bathroom door"
  device_class: door
  unique_id: "binary_sensor.bathroom_door"

- platform: mqtt
  state_topic: "mega1/10"
  value_template: "{{ value_json.value }}"
  name: "Bathroom motion"
  device_class: motion
  unique_id: "binary_sensor.bathroom_motion"

- platform: mqtt
  state_topic: "mega1/5"
  value_template: "{{ value_json.value }}"
  name: "Hall motion"
  device_class: motion
  unique_id: "binary_sensor.hall_motion"

- platform: mqtt
  state_topic: "mega1/#"
  value_template: "{% if value[0] == '{' %}ON{% else %}{% endif %}"
  name: "Mega 1 online"
  device_class: connectivity
  off_delay: 60
  unique_id: "binary_sensor.mega1_online"

- platform: mqtt
  state_topic: "mega2/41"
  value_template: "{{ value_json.value }}"
  name: "Room 1 motion"
  device_class: motion
  unique_id: "binary_sensor.room1_motion"

- platform: mqtt
  state_topic: "mega2/43"
  value_template: "{{ value_json.value }}"
  name: "Corner motion"
  device_class: motion
  unique_id: "binary_sensor.corner_motion"

- platform: mqtt
  state_topic: "mega2/30"
  value_template: "{{ value_json.value }}"
  name: "Door motion"
  device_class: motion
  unique_id: "binary_sensor.door_motion"

- platform: mqtt
  state_topic: "mega2/31"
  value_template: "{{ value_json.value }}"
  name: "Main door"
  device_class: door
  unique_id: "binary_sensor.main_door"

- platform: mqtt
  state_topic: "mega2/#"
  value_template: "{% if value[0] == '{' %}ON{% else %}{% endif %}"
  name: "Mega 2 online"
  device_class: connectivity
  off_delay: 60
  unique_id: "binary_sensor.mega2_online"

- platform: mqtt
  state_topic: "mega3/#"
  value_template: "{% if value[0] == '{' %}ON{% else %}{% endif %}"
  name: "Mega 3 online"
  device_class: connectivity
  off_delay: 70
  unique_id: "binary_sensor.mega3_online"

- platform: mqtt
  state_topic: "mega2/6"
  value_template: "{{ value_json.value }}"
  name: "Mega 2 AC"
  device_class: power
  unique_id: "binary_sensor.mega2_ac"

- platform: mqtt
  state_topic: "mega2/5"
  value_template: "{{ value_json.value }}"
  name: "Mega 2 Battery low"
  device_class: battery
  unique_id: "binary_sensor.mega2_battery"

- platform: mqtt
  state_topic: "mega2/2"
  value_template: "{{ value_json.value }}"
  name: "Room 1 Switch Left"
  unique_id: "binary_sensor.room1_switch_l"

- platform: mqtt
  state_topic: "mega2/0"
  value_template: "{{ value_json.value }}"
  name: "Room 1 Switch Right"
  unique_id: "binary_sensor.room1_switch_r"

- platform: workday
  country: BY
  workdays: [mon, tue, wed, thu, fri]
  excludes: [sat, sun, holiday]

- platform: template
  sensors:
    energy_cheap:
      friendly_name: "Cheap energy"
      device_class: power
      value_template: "{% set hour = states('sensor.time').split(':')[0] | int %}{% if is_state('binary_sensor.workday_sensor', 'on') and hour >= 17 and hour < 22 %}off{% else %}on{% endif %}"

- platform: ping
  host: !secret sw1_ip
  name: "SW1 ping"
  count: 2
  scan_interval: 60

- platform: ping
  host: !secret border_ip
  name: "BORDER ping"
  count: 2
  scan_interval: 60

- platform: ping
  host: !secret gw1_ip
  name: !secret gw1_name
  count: 2
  scan_interval: 60

- platform: ping
  host: !secret gw2_ip
  name: !secret gw2_name
  count: 2
  scan_interval: 60
