# !!! Dont forget to add light to the "auto brightness" script (condition and actions) and to the "on mega ac loss" script.

- platform: mqtt
  name: "Toilet light LED"
  unique_id: "bathroom.toilet_light_led"
  command_topic: "megad_mqtt_bridge/mega1/cmd"
  payload_off: "32e15:0"
  brightness_command_topic: "megad_mqtt_bridge/mega1/cmd-ext-bri/32e15"
  brightness_scale: 100
  on_command_type: 'brightness'

- platform: mqtt
  name: "Bathroom light LED"
  unique_id: "light.bathroom_light_led"
  command_topic: "megad_mqtt_bridge/mega1/cmd"
  payload_off: "32e14:0"
  brightness_command_topic: "megad_mqtt_bridge/mega1/cmd-ext-bri/32e14"
  brightness_scale: 100
  on_command_type: 'brightness'

- platform: mqtt
  name: "Bathroom mirror light LED"
  unique_id: "light.bathroom_mirror_light_led"
  command_topic: "megad_mqtt_bridge/mega1/cmd"
  payload_off: "32e9:0"
  brightness_command_topic: "megad_mqtt_bridge/mega1/cmd-ext-bri/32e9"
  brightness_scale: 100
  on_command_type: 'brightness'

- platform: mqtt
  name: "Door light LED"
  unique_id: "light.door_light_led"
  command_topic: "megad_mqtt_bridge/mega2/cmd"
  payload_off: "38e1:0"
  brightness_command_topic: "megad_mqtt_bridge/mega2/cmd-ext-bri/38e1"
  brightness_scale: 100
  on_command_type: 'brightness'

- platform: mqtt
  name: "Corner light LED"
  unique_id: "light.corner_light_led"
  command_topic: "megad_mqtt_bridge/mega2/cmd"
  payload_off: "38e0:0"
  brightness_command_topic: "megad_mqtt_bridge/mega2/cmd-ext-bri/38e0"
  brightness_scale: 100
  on_command_type: 'brightness'

- platform: mqtt
  name: "Hall light LED"
  unique_id: "light.hall_light_led"
  command_topic: "megad_mqtt_bridge/mega1/cmd"
  payload_off: "32e13:0"
  brightness_command_topic: "megad_mqtt_bridge/mega1/cmd-ext-bri/32e13"
  brightness_scale: 100
  on_command_type: 'brightness'

- platform: mqtt
  name: "LED"
  unique_id: "light.led"
  command_topic: "megad_mqtt_bridge/mega2/cmd"
  payload_off: "38e2:0"
  brightness_command_topic: "megad_mqtt_bridge/mega2/cmd-ext-bri/38e2"
  brightness_scale: 100
  on_command_type: 'brightness'

- platform: mqtt
  name: "Bulbs"
  unique_id: "light.bulbs"
  command_topic: "megad_mqtt_bridge/mega2/cmd"
  payload_off: "14:0"
  payload_on: "14:1"
  state_topic: "megad_mqtt_bridge/mega2/14"
  state_value_template: "14:{%if value_json.value == 'ON'%}1{%else%}0{%endif%}"

- platform: mqtt
  name: "LED yellow"
  unique_id: "light.led_yellow"
  command_topic: "megad_mqtt_bridge/mega2/cmd"
  payload_off: "38e3:0"
  brightness_command_topic: "megad_mqtt_bridge/mega2/cmd-ext-bri/38e3"
  brightness_scale: 100
  on_command_type: 'brightness'

- platform: mqtt
  name: "Kitchen work light LED"
  unique_id: "light.kitchen_work_light_led"
  command_topic: "megad_mqtt_bridge/mega3/cmd"
  payload_off: "39e15:0"
  brightness_command_topic: "megad_mqtt_bridge/mega3/cmd-ext-bri/39e15"
  brightness_scale: 100
  on_command_type: 'brightness'

- platform: mqtt
  name: "Kitchen top storage light LED"
  unique_id: "light.kitchen_top_storage_light_led"
  command_topic: "megad_mqtt_bridge/mega1/cmd"
  payload_off: "32e11:0"
  brightness_command_topic: "megad_mqtt_bridge/mega1/cmd-ext-bri/32e11"
  brightness_scale: 100
  on_command_type: 'brightness'

- platform: mqtt
  name: "Hall storage light LED"
  unique_id: "light.hall_storage_light_led"
  command_topic: "megad_mqtt_bridge/mega1/cmd"
  payload_off: "32e10:0"
  brightness_command_topic: "megad_mqtt_bridge/mega1/cmd-ext-bri/32e10"
  brightness_scale: 100
  on_command_type: 'brightness'

- platform: mqtt
  schema: json
  name: "Balcony RGB LED"
  state_topic: "esp_rgb_light/rgb1"
  command_topic: "esp_rgb_light/rgb1/set"
  brightness: true
  rgb: true
  optimistic: false
  qos: 0

- platform: mqtt
  name: "Kitchen fridge storage light LED"
  unique_id: "light.kitchen_fridge_storage_light_led"
  command_topic: "megad_mqtt_bridge/mega3/cmd"
  payload_off: "39e14:0"
  brightness_command_topic: "megad_mqtt_bridge/mega3/cmd-ext-bri/39e14"
  brightness_scale: 100
  on_command_type: 'brightness'

- platform: mqtt
  name: "Toilet bulb"
  unique_id: "light.toilet_bulb"
  command_topic: "megad_mqtt_bridge/mega3/cmd"
  payload_off: "25:0"
  payload_on: "25:1"
  state_topic: "megad_mqtt_bridge/mega3/25"
  state_value_template: "25:{%if value_json.value == 'ON'%}1{%else%}0{%endif%}"

- platform: mqtt
  name: "Bathroom bulb"
  unique_id: "light.bathroom_bulb"
  command_topic: "megad_mqtt_bridge/mega3/cmd"
  payload_off: "26:0"
  payload_on: "26:1"
  state_topic: "megad_mqtt_bridge/mega3/26"
  state_value_template: "26:{%if value_json.value == 'ON'%}1{%else%}0{%endif%}"

- platform: mqtt
  name: "Hall bulb"
  unique_id: "light.hall_bulb"
  command_topic: "megad_mqtt_bridge/mega3/cmd"
  payload_off: "27:0"
  payload_on: "27:1"
  state_topic: "megad_mqtt_bridge/mega3/27"
  state_value_template: "27:{%if value_json.value == 'ON'%}1{%else%}0{%endif%}"

- platform: mqtt
  name: "Kitchen left"
  unique_id: "light.kitchen_left"
  command_topic: "megad_mqtt_bridge/mega3/cmd"
  payload_off: "9:0"
  payload_on: "9:1"
  state_topic: "megad_mqtt_bridge/mega3/9"
  state_value_template: "9:{%if value_json.value == 'ON'%}1{%else%}0{%endif%}"

- platform: mqtt
  name: "Kitchen center"
  unique_id: "light.kitchen_center"
  command_topic: "megad_mqtt_bridge/mega3/cmd"
  payload_off: "8:0"
  payload_on: "8:1"
  state_topic: "megad_mqtt_bridge/mega3/8"
  state_value_template: "8:{%if value_json.value == 'ON'%}1{%else%}0{%endif%}"

- platform: mqtt
  name: "Kitchen right"
  unique_id: "light.kitchen_right"
  command_topic: "megad_mqtt_bridge/mega3/cmd"
  payload_off: "7:0"
  payload_on: "7:1"
  state_topic: "megad_mqtt_bridge/mega3/7"
  state_value_template: "7:{%if value_json.value == 'ON'%}1{%else%}0{%endif%}"
