- platform: mqtt
  name: "Toilet light LED"
  unique_id: "bathroom.toilet_light_led"
  command_topic: "mega1/cmd"
  payload_off: "32e15:0"
  brightness_command_topic: "mega1/cmd-ext-bri/32e15"
  brightness_scale: 100
  on_command_type: 'brightness'

- platform: mqtt
  name: "Bathroom light LED"
  unique_id: "light.bathroom_light_led"
  command_topic: "mega1/cmd"
  payload_off: "32e14:0"
  brightness_command_topic: "mega1/cmd-ext-bri/32e14"
  brightness_scale: 100
  on_command_type: 'brightness'

- platform: mqtt
  name: "Door light LED"
  unique_id: "light.door_light_led"
  command_topic: "mega2/cmd"
  payload_off: "38e1:0"
  brightness_command_topic: "mega2/cmd-ext-bri/38e1"
  brightness_scale: 100
  on_command_type: 'brightness'

- platform: mqtt
  name: "Corner light LED"
  unique_id: "light.corner_light_led"
  command_topic: "mega2/cmd"
  payload_off: "38e0:0"
  brightness_command_topic: "mega2/cmd-ext-bri/38e0"
  brightness_scale: 100
  on_command_type: 'brightness'

- platform: mqtt
  name: "Hall light LED"
  unique_id: "light.hall_light_led"
  command_topic: "mega1/cmd"
  payload_off: "32e13:0"
  brightness_command_topic: "mega1/cmd-ext-bri/32e13"
  brightness_scale: 100
  on_command_type: 'brightness'

- platform: mqtt
  name: "LED"
  unique_id: "light.led"
  command_topic: "mega2/cmd"
  payload_off: "38e2:0"
  brightness_command_topic: "mega2/cmd-ext-bri/38e2"
  brightness_scale: 100
  on_command_type: 'brightness'

- platform: mqtt
  name: "LED yellow"
  unique_id: "light.led_yellow"
  command_topic: "mega2/cmd"
  payload_off: "38e3:0"
  brightness_command_topic: "mega2/cmd-ext-bri/38e3"
  brightness_scale: 100
  on_command_type: 'brightness'

- platform: mqtt
  name: "Bulbs"
  state_topic: "s3home/clunet/bulbs_3"
  command_topic: "s3home/clunet/bulbs_3/set"
  brightness_command_topic: "s3home/clunet/bulbs_3/bri/set"
  brightness_state_topic: "s3home/clunet/bulbs_3/bri"
  brightness_scale: 5
  unique_id: "light.bulbs"

- platform: mqtt
  name: LED угол
  state_topic: s3home/clunet/led_force_4
  command_topic: s3home/clunet/led_force_4/set
  unique_id: "light.force_4"

- platform: mqtt
  name: LED дверь
  state_topic: s3home/clunet/led_force_5
  command_topic: s3home/clunet/led_force_5/set
  unique_id: "light.force_5"

- platform: mqtt
  name: LED коридор
  state_topic: s3home/clunet/led_force_7
  command_topic: s3home/clunet/led_force_7/set
  unique_id: "light.force_7"
