- platform: mqtt
  unique_id: "switch.tion3s_power"
  name: "Tion power"
  state_topic: "bt_bridge/tion3s/state"
  command_topic: "bt_bridge/tion3s/state/set"

- platform: mqtt
  unique_id: "switch.tion3s_heater"
  name: "Tion heater"
  icon: mdi:fire
  state_topic: "bt_bridge/tion3s/heater"
  command_topic: "bt_bridge/tion3s/heater/set"

- platform: mqtt
  unique_id: "tion3s_sound"
  name: "Tion sound"
  icon: mdi:music-note
  state_topic: "bt_bridge/tion3s/sound"
  command_topic: "bt_bridge/tion3s/sound/set"

- platform: mqtt
  unique_id: "switch.rhf3310s_power"
  name: "RHF-3310S power"
  state_topic: "bt_bridge/rhf3310s/on"
  command_topic: "bt_bridge/rhf3310s/on/set"

- platform: mqtt
  unique_id: "switch.rhf3310s_heater"
  name: "RHF-3310S heater"
  icon: mdi:fire
  state_topic: "bt_bridge/rhf3310s/heater"
  command_topic: "bt_bridge/rhf3310s/heater/set"

- platform: command_line
  switches:
    balcony_rgb_light:
      friendly_name: "Balcony animated light"
      command_on: !secret balcony_rgb_light_script
      ccommand_off: "/usr/bin/pkill -f rgb_led_animated || /bin/true"
      command_state: "ps x | grep -v grep | grep rgb_led_animated"
