- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega2/10"
  value_template: "{{ value_json.value.a63532020800|float * 8 }}"
  name: "1W Room 1 temp"
  unit_of_measurement: "°C"
  device_class: temperature
  unique_id: "sensor.1w_room_1_temp"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega2/10"
  value_template: "{{ value_json.value.127f44060000 }}"
  name: "1W Outdoor temp"
  unit_of_measurement: "°C"
  device_class: temperature
  unique_id: "sensor.1w_outdoor_temp"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega2/10"
  value_template: "{{ value_json.value.7fbb44060000 }}"
  name: "1W Vent temp"
  unit_of_measurement: "°C"
  device_class: temperature
  unique_id: "sensor.1w_vent_temp"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega2/10"
  value_template: "{{ value_json.value.f2dc74020800|float * 8 }}"
  name: "1W Heating 1 temp"
  unit_of_measurement: "°C"
  device_class: temperature
  unique_id: "sensor.1w_heating_1_temp"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega2/10"
  value_template: "{{ value_json.value.888344060000 }}"
  name: "1W Room 2 door temp"
  unit_of_measurement: "°C"
  device_class: temperature
  unique_id: "sensor.1w_room_2_door_temp"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega2/10"
  value_template: "{{ value_json.value.e66b45060000 }}"
  name: "1W Room 2 pc temp"
  unit_of_measurement: "°C"
  device_class: temperature
  unique_id: "sensor.1w_room_2_pc_temp"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega2/10"
  value_template: "{{ value_json.value.ee6d7a1f1602 }}"
  name: "1W Heating 2 temp"
  unit_of_measurement: "°C"
  device_class: temperature
  unique_id: "sensor.1w_heating_2_temp"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega2/10"
  value_template: "{{ value_json.value.798d45060000 }}"
  name: "1W Room 3 door temp"
  unit_of_measurement: "°C"
  device_class: temperature
  unique_id: "sensor.1w_room_3_door_temp"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega2/10"
  value_template: "{{ value_json.value.69cf74020800|float * 8 }}"
  name: "1W Room 3 bed temp"
  unit_of_measurement: "°C"
  device_class: temperature
  unique_id: "sensor.1w_room_3_bed_temp"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega2/10"
  value_template: "{{ value_json.value.eed02f231601 }}"
  name: "1W Kitchen temp"
  unit_of_measurement: "°C"
  device_class: temperature
  unique_id: "sensor.1w_kitchen_temp"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega2/10"
  value_template: "{{ value_json.value.eef9901f1602 }}"
  name: "1W Heating 3 temp"
  unit_of_measurement: "°C"
  device_class: temperature
  unique_id: "sensor.1w_heating_3_temp"
