- platform: rest
  resource: !secret mega2_1w
  name: "mega2_1w_raw"

- platform: template
  sensors:
    1w_room_1_temp:
      friendly_name: "1W Room 1 temp"
      value_template: "{% for item in states.sensor.mega2_1w_raw.state.split(';') %}{% set v = item.split(':')%}{% if v[0] == 'a63532020800'%}{{v[1]|float * 8}}{%endif%}{% endfor %}"
      unit_of_measurement: "°C"
      device_class: temperature
    1w_outdoor_temp:
      friendly_name: "1W Outdoor temp"
      value_template: "{% for item in states.sensor.mega2_1w_raw.state.split(';') %}{% set v = item.split(':')%}{% if v[0] == '127f44060000'%}{{v[1]|float}}{%endif%}{% endfor %}"
      unit_of_measurement: "°C"
      device_class: temperature
    1w_vent_temp:
      friendly_name: "1W Vent temp"
      value_template: "{% for item in states.sensor.mega2_1w_raw.state.split(';') %}{% set v = item.split(':')%}{% if v[0] == '7fbb44060000'%}{{v[1]|float}}{%endif%}{% endfor %}"
      unit_of_measurement: "°C"
      device_class: temperature
    1w_heating_1_temp:
      friendly_name: "1W Heating 1 temp"
      value_template: "{% for item in states.sensor.mega2_1w_raw.state.split(';') %}{% set v = item.split(':')%}{% if v[0] == 'f2dc74020800'%}{{v[1]|float * 8}}{%endif%}{% endfor %}"
      unit_of_measurement: "°C"
      device_class: temperature
    1w_room_2_door_temp:
      friendly_name: "1W Room 2 door temp"
      value_template: "{% for item in states.sensor.mega2_1w_raw.state.split(';') %}{% set v = item.split(':')%}{% if v[0] == '888344060000'%}{{v[1]|float}}{%endif%}{% endfor %}"
      unit_of_measurement: "°C"
      device_class: temperature
    1w_room_2_pc_temp:
      friendly_name: "1W Room 2 pc temp"
      value_template: "{% for item in states.sensor.mega2_1w_raw.state.split(';') %}{% set v = item.split(':')%}{% if v[0] == 'e66b45060000'%}{{v[1]|float}}{%endif%}{% endfor %}"
      unit_of_measurement: "°C"
      device_class: temperature
    1w_heating_2_temp:
      friendly_name: "1W Heating 2 temp"
      value_template: "{% for item in states.sensor.mega2_1w_raw.state.split(';') %}{% set v = item.split(':')%}{% if v[0] == 'ee6d7a1f1602'%}{{v[1]|float}}{%endif%}{% endfor %}"
      unit_of_measurement: "°C"
      device_class: temperature
    1w_room_3_door_temp:
      friendly_name: "1W Room 3 door temp"
      value_template: "{% for item in states.sensor.mega2_1w_raw.state.split(';') %}{% set v = item.split(':')%}{% if v[0] == '798d45060000'%}{{v[1]|float}}{%endif%}{% endfor %}"
      unit_of_measurement: "°C"
      device_class: temperature
    1w_room_3_bed_temp:
      friendly_name: "1W Room 3 bed temp"
      value_template: "{% for item in states.sensor.mega2_1w_raw.state.split(';') %}{% set v = item.split(':')%}{% if v[0] == '69cf74020800'%}{{v[1]|float * 8}}{%endif%}{% endfor %}"
      unit_of_measurement: "°C"
      device_class: temperature
    1w_kitchen_temp:
      friendly_name: "1W Kitchen temp"
      value_template: "{% for item in states.sensor.mega2_1w_raw.state.split(';') %}{% set v = item.split(':')%}{% if v[0] == 'eed02f231601'%}{{v[1]|float}}{%endif%}{% endfor %}"
      unit_of_measurement: "°C"
      device_class: temperature
    1w_heating_3_temp:
      friendly_name: "1W Heating 3 temp"
      value_template: "{% for item in states.sensor.mega2_1w_raw.state.split(';') %}{% set v = item.split(':')%}{% if v[0] == 'eef9901f1602'%}{{v[1]|float}}{%endif%}{% endfor %}"
      unit_of_measurement: "°C"
      device_class: temperature
