- platform: mqtt
  state_topic: "mega2/10"
  value_template: "{{ value_json.value.a63532020800 * 8 }}"
  name: "1W Room 1 temp"
  unit_of_measurement: "°C"
  device_class: temperature

- platform: mqtt
  state_topic: "mega2/10"
  value_template: "{{ value_json.value.127f44060000 }}"
  name: "1W Outdoor temp"
  unit_of_measurement: "°C"
  device_class: temperature

- platform: mqtt
  state_topic: "mega2/10"
  value_template: "{{ value_json.value.7fbb44060000 }}"
  name: "1W Vent temp"
  unit_of_measurement: "°C"
  device_class: temperature

- platform: mqtt
  state_topic: "mega2/10"
  value_template: "{{ value_json.value.f2dc74020800 * 8 }}"
  name: "1W Heating 1"
  unit_of_measurement: "°C"
  device_class: temperature

- platform: mqtt
  state_topic: "mega2/10"
  value_template: "{{ value_json.value.888344060000 }}"
  name: "1W Room 2 door temp"
  unit_of_measurement: "°C"
  device_class: temperature

- platform: mqtt
  state_topic: "mega2/10"
  value_template: "{{ value_json.value.e66b45060000 }}"
  name: "1W Room 2 pc temp"
  unit_of_measurement: "°C"
  device_class: temperature

- platform: mqtt
  state_topic: "mega2/10"
  value_template: "{{ value_json.value.ee6d7a1f1602 }}"
  name: "1W Heating 2 temp"
  unit_of_measurement: "°C"
  device_class: temperature

- platform: mqtt
  state_topic: "mega2/10"
  value_template: "{{ value_json.value.798d45060000 }}"
  name: "1W Room 3 door temp"
  unit_of_measurement: "°C"
  device_class: temperature

- platform: mqtt
  state_topic: "mega2/10"
  value_template: "{{ value_json.value.69cf74020800 * 8 }}"
  name: "1W Room 3 bed temp"
  unit_of_measurement: "°C"
  device_class: temperature

- platform: mqtt
  state_topic: "mega2/10"
  value_template: "{{ value_json.value.eed02f231601 }}"
  name: "1W Kitchen temp"
  unit_of_measurement: "°C"
  device_class: temperature

- platform: mqtt
  state_topic: "mega2/10"
  value_template: "{{ value_json.value.eef9901f1602 }}"
  name: "1W Heating 3 temp"
  unit_of_measurement: "°C"
  device_class: temperature
