- platform: mqtt
  state_topic: "ups/apc3000/battery.voltage"
  name: "APC3000 Battery Voltage"
  device_class: voltage
  unit_of_measurement: "V"
  unique_id: "sensor.apc3000_battery_voltage"
  value_template: "{{ value | int / 10 | float }}"

- platform: mqtt
  state_topic: "ups/apc3000/battery.charge"
  name: "APC3000 Battery Charge"
  device_class: battery
  unit_of_measurement: "%"
  unique_id: "sensor.apc3000_battery_charge"
  value_template: "{{ value | int / 10 | float }}"

- platform: mqtt
  state_topic: "ups/apc3000/battery.current"
  name: "APC3000 Battery Current"
  device_class: current
  unit_of_measurement: "A"
  unique_id: "sensor.apc3000_battery_current"

- platform: mqtt
  state_topic: "ups/apc3000/input.voltage"
  name: "APC3000 Input Voltage"
  device_class: voltage
  unit_of_measurement: "V"
  unique_id: "sensor.apc3000_input_voltage"
  value_template: "{{ value | int / 10 | float }}"

- platform: mqtt
  state_topic: "ups/apc3000/ups.load"
  name: "APC3000 Load"
  unit_of_measurement: "%"
  icon: "mdi:gauge"
  unique_id: "sensor.apc3000_load"

- platform: mqtt
  state_topic: "ups/apc3000/output.current"
  name: "APC3000 Output Current"
  device_class: current
  unit_of_measurement: "A"
  unique_id: "sensor.apc3000_output_current"

- platform: mqtt
  state_topic: "ups/apc3000/output.frequency"
  name: "APC3000 Output Frequency"
  unit_of_measurement: "Hz"
  icon: mdi:flash
  unique_id: "sensor.apc3000_output_frequency"
  value_template: "{{ value | int / 10 | float }}"

- platform: mqtt
  state_topic: "ups/apc3000/output.voltage"
  name: "APC3000 Output Voltage"
  device_class: voltage
  unit_of_measurement: "V"
  unique_id: "sensor.apc3000_output_voltage"
  value_template: "{{ value | int / 10 | float }}"

- platform: mqtt
  state_topic: "ups/apc3000/ups.status"
  name: "APC3000 Status"
  icon: mdi:information-outline
  unique_id: "sensor.apc3000_status"

- platform: mqtt
  state_topic: "ups/apc3000/ups.status_text"
  name: "APC3000 Status Data"
  icon: mdi:information-outline
  unique_id: "sensor.apc3000_status_data"
