- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega1/9/max44009"
  value_template: "{{ value_json.value.temp }}"
  name: "Bathroom light"
  unit_of_measurement: "lx"
  device_class: illuminance
  unique_id: "sensor.bathroom_light"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega1/9"
  value_template: "{{ value_json.value.temp }}"
  name: "Bathroom temp"
  unit_of_measurement: "°C"
  device_class: temperature
  unique_id: "sensor.bathroom_temp"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega1/9"
  value_template: "{{ value_json.value.hum }}"
  name: "Bathroom humidity"
  unit_of_measurement: "%"
  device_class: humidity
  unique_id: "sensor.bathroom_humidity"
