- platform: rest
  resource: !secret mega2_light_corner
  name: "Corner light"
  unit_of_measurement: "lx"
  device_class: illuminance

- platform: mqtt
  state_topic: "mega2/42"
  value_template: "{{ value_json.value.temp }}"
  name: "Corner temp"
  unit_of_measurement: "°C"
  device_class: temperature
  unique_id: "sensor.corner_temp"

- platform: mqtt
  state_topic: "mega2/42"
  value_template: "{{ value_json.value.hum }}"
  name: "Corner humidity"
  unit_of_measurement: "%"
  device_class: humidity
  unique_id: "sensor.corner_humidity"
