- platform: rest
  resource: !secret mega2_light_door
  name: "Door light"
  unit_of_measurement: "lx"
  device_class: illuminance

- platform: mqtt
  state_topic: "mega2/44"
  value_template: "{{ value_json.value.temp }}"
  name: "Door temp"
  unit_of_measurement: "°C"
  device_class: temperature
  unique_id: "sensor.door_temp"

- platform: mqtt
  state_topic: "mega2/44"
  value_template: "{{ value_json.value.hum }}"
  name: "Door humidity"
  unit_of_measurement: "%"
  device_class: humidity
  unique_id: "sensor.door_humidity"
