- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega1/4/max44009"
  value_template: "{{ value_json.value.light }}"
  name: "Hall light"
  unit_of_measurement: "lx"
  device_class: illuminance
  unique_id: "sensor.hall_light"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega1/4"
  value_template: "{{ value_json.value.temp }}"
  name: "Hall temp"
  unit_of_measurement: "°C"
  device_class: temperature
  unique_id: "sensor.hall_temp"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega1/4"
  value_template: "{{ value_json.value.hum }}"
  name: "Hall humidity"
  unit_of_measurement: "%"
  device_class: humidity
  unique_id: "sensor.hall_humidity"
