- platform: rest
  resource: !secret mega1_light_hall
  name: "Hall light"
  unit_of_measurement: "lx"
  device_class: illuminance

- platform: mqtt
  state_topic: "mega1/4"
  value_template: "{{ value_json.value.temp }}"
  name: "Hall temp"
  unit_of_measurement: "°C"
  device_class: temperature
  unique_id: "sensor.hall_temp"

- platform: mqtt
  state_topic: "mega1/4"
  value_template: "{{ value_json.value.hum }}"
  name: "Hall humidity"
  unit_of_measurement: "%"
  device_class: humidity
  unique_id: "sensor.hall_humidity"
