- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega3/0/max44009"
  value_template: "{{ value_json.value.light }}"
  name: "Kitchen light"
  unit_of_measurement: "lx"
  device_class: illuminance
  unique_id: "sensor.kitchen_light"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega3/0"
  value_template: "{{ value_json.value.temp }}"
  name: "Kitchen temp"
  unit_of_measurement: "°C"
  device_class: temperature
  unique_id: "sensor.kitchen_temp"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega3/0"
  value_template: "{{ value_json.value.hum }}"
  name: "Kitchen humidity"
  unit_of_measurement: "%"
  device_class: humidity
  unique_id: "sensor.kitchen_humidity"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega3/0/t67xx"
  value_template: "{{ value_json.value.co2 }}"
  name: "Kitchen CO2"
  unit_of_measurement: "ppm"
  unique_id: "sensor.kitchen_co2"
