- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega2/8"
  value_template: "{{ value_json.value.temp }}"
  name: "Mega 2 temp"
  unit_of_measurement: "°C"
  device_class: temperature
  unique_id: "sensor.mega2_temp"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega2/8"
  value_template: "{{ value_json.value.hum }}"
  name: "Mega 2 humidity"
  unit_of_measurement: "%"
  device_class: humidity
  unique_id: "sensor.mega2_humidity"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega2/8"
  value_template: "{{ value_json.value.press }}"
  name: "Mega 2 pressure"
  unit_of_measurement: "mm Hg"
  device_class: pressure
  unique_id: "sensor.mega2_pressure"
