- platform: nut
  name: "APC Smart-UPS 1500"
  host: rpi-main.lan
  port: 3493
  alias: apc1500
  resources:
    - battery.charge
    - battery.voltage
    - input.voltage
    - output.current
    - output.frequency
    - output.voltage
    - ups.load
    - ups.status
    - ups.status.display
