- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega2/9/max44009"
  value_template: "{{ value_json.value.light }}"
  name: "Outdoor light"
  unit_of_measurement: "lx"
  device_class: illuminance
  unique_id: "sensor.outdoor_light"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega2/9"
  value_template: "{{ value_json.value.temp }}"
  name: "Outdoor temp"
  unit_of_measurement: "°C"
  device_class: temperature
  unique_id: "sensor.outdoor_temp"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega2/9"
  value_template: "{{ value_json.value.hum }}"
  name: "Outdoor humidity"
  unit_of_measurement: "%"
  device_class: humidity
  unique_id: "sensor.outdoor_humidity"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega3/44/max44009"
  value_template: "{{ value_json.value.light }}"
  name: "Outdoor 2 light"
  unit_of_measurement: "lx"
  device_class: illuminance
  unique_id: "sensor.outdoor_2_light"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega3/44"
  value_template: "{{ value_json.value.temp }}"
  name: "Outdoor 2 temp"
  unit_of_measurement: "°C"
  device_class: temperature
  unique_id: "sensor.outdoor_2_temp"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega3/44"
  value_template: "{{ value_json.value.hum }}"
  name: "Outdoor 2 humidity"
  unit_of_measurement: "%"
  device_class: humidity
  unique_id: "sensor.outdoor_2_humidity"
