- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega1/1/max44009"
  name: "Room 3 light"
  value_template: "{{ value_json.value.light }}"
  unit_of_measurement: "lx"
  device_class: illuminance
  unique_id: "sensor.room3_light"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega1/1"
  value_template: "{{ value_json.value.temp }}"
  name: "Room 3 temp"
  unit_of_measurement: "°C"
  device_class: temperature
  unique_id: "sensor.room3_temp"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega1/1"
  value_template: "{{ value_json.value.hum }}"
  name: "Room 3 humidity"
  unit_of_measurement: "%"
  device_class: humidity
  unique_id: "sensor.room3_humidity"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega1/1/t67xx"
  value_template: "{{ value_json.value.co2 }}"
  name: "Room 3 CO2"
  unit_of_measurement: "ppm"
  unique_id: "sensor.room3_co2"
