- platform: rest
  resource: !secret mega2_light_room1
  name: "Room 1 light"
  unit_of_measurement: "lx"
  device_class: illuminance

- platform: mqtt
  state_topic: "mega2/40"
  value_template: "{{ value_json.value.temp }}"
  name: "Room 1 temp"
  unit_of_measurement: "°C"
  device_class: temperature
  unique_id: "sensor.room1_temp"

- platform: mqtt
  state_topic: "mega2/40"
  value_template: "{{ value_json.value.hum }}"
  name: "Room 1 humidity"
  unit_of_measurement: "%"
  device_class: humidity
  unique_id: "sensor.room1_humidity"

- platform: rest
  resource: !secret mega2_co2_room1
  name: "Room 1 CO2"
  unit_of_measurement: "ppm"

- platform: rest
  resource: !secret mega2_water_tree
  name: "Christmas tree water level"
  unit_of_measurement: "%"
  value_template: "{%set l=100-(((value|float)-4.4)/0.23)%}{%if l>100%}100{%elif l<0%}0{%else%}{{l}}{%endif%}" #Lmin = 4.4, Lbucket=23, Lmax=Lmin+Lbucket=27.4, 0.23=(Lmax-Lmin)/100
