- platform: rest
  resource: !secret mega2_light_room1
  name: "Room 1 light"
  unit_of_measurement: "lx"
  device_class: illuminance

- platform: mqtt
  state_topic: "mega2/40"
  value_template: "{{ value_json.value.temp }}"
  name: "Room 1 temp"
  unit_of_measurement: "°C"
  device_class: temperature
  unique_id: "sensor.room1_temp"

- platform: mqtt
  state_topic: "mega2/40"
  value_template: "{{ value_json.value.hum }}"
  name: "Room 1 humidity"
  unit_of_measurement: "%"
  device_class: humidity
  unique_id: "sensor.room1_humidity"

- platform: rest
  resource: !secret mega2_co2_room1
  name: "Room 1 CO2"
  unit_of_measurement: "ppm"
