- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega2/33/max44009"
  name: "Room 2 light"
  value_template: "{{ value_json.value.light }}"
  unit_of_measurement: "lx"
  device_class: illuminance
  unique_id: "sensor.room2_light"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega2/33"
  value_template: "{{ value_json.value.temp }}"
  name: "Room 2 temp"
  unit_of_measurement: "°C"
  device_class: temperature
  unique_id: "sensor.room2_temp"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega2/33"
  value_template: "{{ value_json.value.hum }}"
  name: "Room 2 humidity"
  unit_of_measurement: "%"
  device_class: humidity
  unique_id: "sensor.room2_humidity"
