- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega1/36"
  value_template: "{{ value_json.value.ee862f231601 }}"
  name: "Water In HOT temp"
  unit_of_measurement: "°C"
  device_class: temperature
  unique_id: "sensor.toilet_water1_temp"

- platform: mqtt
  state_topic: "megad_mqtt_bridge/mega1/36"
  value_template: "{{ value_json.value.eed1a31f1602 }}"
  name: "Water In COLD temp"
  unit_of_measurement: "°C"
  device_class: temperature
  unique_id: "sensor.toilet_water12_temp"

- platform: mqtt
  state_topic: "mega1/30"
  value_template: "{{ value_json.value }}"
  name: "Toilet pressure"
  unit_of_measurement: "Bar"
  device_class: pressure
  unique_id: "sensor.toilet_pressure"
